
package com.unitn.process_centric_service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PCService", targetNamespace = "http://process_centric_service.unitn.com/", wsdlLocation = "https://calm-thicket-15896.herokuapp.com/ws/pcservice?wsdl")
public class PCService
    extends Service
{

    private final static URL PCSERVICE_WSDL_LOCATION;
    private final static WebServiceException PCSERVICE_EXCEPTION;
    private final static QName PCSERVICE_QNAME = new QName("http://process_centric_service.unitn.com/", "PCService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://calm-thicket-15896.herokuapp.com/ws/pcservice?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PCSERVICE_WSDL_LOCATION = url;
        PCSERVICE_EXCEPTION = e;
    }

    public PCService() {
        super(__getWsdlLocation(), PCSERVICE_QNAME);
    }

    public PCService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PCSERVICE_QNAME, features);
    }

    public PCService(URL wsdlLocation) {
        super(wsdlLocation, PCSERVICE_QNAME);
    }

    public PCService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PCSERVICE_QNAME, features);
    }

    public PCService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PCService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ProcessCentricService
     */
    @WebEndpoint(name = "PCSImplPort")
    public ProcessCentricService getPCSImplPort() {
        return super.getPort(new QName("http://process_centric_service.unitn.com/", "PCSImplPort"), ProcessCentricService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ProcessCentricService
     */
    @WebEndpoint(name = "PCSImplPort")
    public ProcessCentricService getPCSImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://process_centric_service.unitn.com/", "PCSImplPort"), ProcessCentricService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PCSERVICE_EXCEPTION!= null) {
            throw PCSERVICE_EXCEPTION;
        }
        return PCSERVICE_WSDL_LOCATION;
    }

}
