
package com.unitn.process_centric_service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.unitn.local_database.UserData;
import com.unitn.storage_service.Goal;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ProcessCentricService", targetNamespace = "http://process_centric_service.unitn.com/")
@XmlSeeAlso({
    com.unitn.local_database.ObjectFactory.class,
    com.unitn.process_centric_service.ObjectFactory.class,
    com.unitn.storage_service.ObjectFactory.class
})
public interface ProcessCentricService {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDescription", targetNamespace = "http://process_centric_service.unitn.com/", className = "com.unitn.process_centric_service.GetDescription")
    @ResponseWrapper(localName = "getDescriptionResponse", targetNamespace = "http://process_centric_service.unitn.com/", className = "com.unitn.process_centric_service.GetDescriptionResponse")
    @Action(input = "http://process_centric_service.unitn.com/ProcessCentricService/getDescriptionRequest", output = "http://process_centric_service.unitn.com/ProcessCentricService/getDescriptionResponse")
    public String getDescription();

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "userExists", targetNamespace = "http://process_centric_service.unitn.com/", className = "com.unitn.process_centric_service.UserExists")
    @ResponseWrapper(localName = "userExistsResponse", targetNamespace = "http://process_centric_service.unitn.com/", className = "com.unitn.process_centric_service.UserExistsResponse")
    @Action(input = "http://process_centric_service.unitn.com/ProcessCentricService/userExistsRequest", output = "http://process_centric_service.unitn.com/ProcessCentricService/userExistsResponse")
    public boolean userExists(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "registerNewUser", targetNamespace = "http://process_centric_service.unitn.com/", className = "com.unitn.process_centric_service.RegisterNewUser")
    @ResponseWrapper(localName = "registerNewUserResponse", targetNamespace = "http://process_centric_service.unitn.com/", className = "com.unitn.process_centric_service.RegisterNewUserResponse")
    @Action(input = "http://process_centric_service.unitn.com/ProcessCentricService/registerNewUserRequest", output = "http://process_centric_service.unitn.com/ProcessCentricService/registerNewUserResponse")
    public boolean registerNewUser(
        @WebParam(name = "arg0", targetNamespace = "")
        UserData arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "saveGoal", targetNamespace = "http://process_centric_service.unitn.com/", className = "com.unitn.process_centric_service.SaveGoal")
    @ResponseWrapper(localName = "saveGoalResponse", targetNamespace = "http://process_centric_service.unitn.com/", className = "com.unitn.process_centric_service.SaveGoalResponse")
    @Action(input = "http://process_centric_service.unitn.com/ProcessCentricService/saveGoalRequest", output = "http://process_centric_service.unitn.com/ProcessCentricService/saveGoalResponse")
    public boolean saveGoal(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        Goal arg1);

}
